name: outworking_frontend_deploy
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy connect Server Frontend
        env:
          AWS_HOST: ${{secrets.AWS_HOST}}
          AWS_USER: ${{secrets.AWS_USER}}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #        Github Action Runner 설정
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$AWS_HOST" >> ~/.ssh/known_hosts
          ssh $AWS_USER@$AWS_HOST "
            cd /home/$AWS_USER/outwork/frontend/outworking_frontend && \
            git pull origin main && \
            npm install && \
            npm run build && \
            cp -r dist/* /var/www/html/outwork/
          "
          
          
          

